name: Create Release

on:
  pull_request:

jobs:
  build:
    name: Create Release

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        with:
          github-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
      - run: echo "${{ steps.PR.outputs.number }} ${{ steps.PR.outputs.body }}"
      - name: Generate name for title
        id: title
        run: echo "::set-output name=title::$(date +'%Y/%m/%d at %H:%M')"
      - name: Generate name for tag
        id: tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d-%H%M')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.title.outputs.title }}
          draft: false
          prerelease: false
          body: ${{ steps.PR.outputs.pr.body }}
