name: Create Release

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  creatingRelease:
    if: startsWith(github.head_ref, 'release/')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lock pull request
        uses: sudo-bot/action-pull-request-lock@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
      - name: Set Timezone
        id: setTimezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Denver
      - name: Generate names for title and tag
        if: steps.setTimezone.conclusion == 'success'
        id: namesForTitleAndTag
        run: |
          echo "tag=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo "title=$(date +'%Y/%m/%d at %H:%M')" >> $GITHUB_OUTPUT
      - name: Create Release
        if: steps.namesForTitleAndTag.conclusion == 'success'
        id: createRelease
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.namesForTitleAndTag.outputs.tag }}"
          name: "${{ steps.namesForTitleAndTag.outputs.title }}"
          draft: true
          body: ${{ github.event.pull_request.body }}
      - name: Edit PR (Adding link to created release)
        if: steps.createRelease.conclusion == 'success'
        uses: seripap/pr-update-action@v3.1.6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: "main"
          body-template: |
            :warning: Please do not edit or delete next line of PR body :warning:
            ${{ steps.namesForTitleAndTag.outputs.title }} - [View Release](${{ steps.createRelease.outputs.html_url }})
          body-update-action: "suffix"
