on:
  pull_request:

name: Create Release

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: windows-latest
    steps:
      - name: Generate name for tag
        id: tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d-%H%M')"
      - name: Create Release
        run: gh release create ${{ steps.tag.outputs.tag }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
