name: Create Release

on:
  pull_request:

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate name for tag
        id: tag
        run: echo "::set-output name=tag::$(date +'%Y/%m/%d-%H/%M')"
      - name: Create Release
        run: gh release create ${{ steps.tag.outputs.tag }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
