name: Create Release

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  creatingRelease:
    if: startsWith(github.head_ref, 'release/')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Timezone
        id: setTimezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Denver
      - name: Get PR
        uses: 8BitJonny/gh-get-current-pr@v2.1.3
        id: PR
        with:
          github-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Generate names for title and tag
        if: steps.setTimezone.conclusion == 'success'
        id: namesForTitleAndTag
        run: |
          echo "tag=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo "title=$(date +'%Y/%m/%d at %H:%M')" >> $GITHUB_OUTPUT
      - name: Create Release
        if: steps.namesForTitleAndTag.conclusion == 'success'
        id: createRelease
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.namesForTitleAndTag.outputs.tag }}"
          name: "${{ steps.namesForTitleAndTag.outputs.title }}"
          draft: true
          body: ${{ steps.PR.outputs.pr_body }}
      - name: Edit PR (Adding link to created release)
        if: steps.createRelease.conclusion == 'success'
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: ".*"
          body-template: |
            ${{ steps.namesForTitleAndTag.outputs.title }} - [View Release](${{ steps.createRelease.outputs.html_url }})
          body-update-action: "suffix"
