name: Create Release

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  creatingRelease:
    if: startsWith(github.head_ref, 'release/')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        with:
          github-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "CST"
      - name: Generate names for title and tag
        id: namesForTitleAndTag
        run: |
          echo "{tag}={$(date +'%Y%m%d-%H%M')}" >> $GITHUB_STATE
          echo "{title}={$(date +'%Y/%m/%d at %H:%M')}" >> $GITHUB_STATE
      - name: Test
        run: echo "Tag - ${{ env.tag }}, title - ${{ env.TITLE }}"
      - name: Create Release
        id: createRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.tag }}"
          release_name: "${{ env.title }}"
          draft: true
          prerelease: false
          body: ${{ steps.PR.outputs.pr_body }}
      - name: Edit PR (Adding link to created release)
        if: steps.createRelease.conclusion == 'success'
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: ".*"
          body-template: |
            ${{ env.title }} - [View Release](${{ steps.createRelease.outputs.html_url }})
          body-update-action: "suffix"
