name: Create Release

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    name: Create Release

    runs-on: windows-latest

    if: startsWith(github.head_ref, 'release/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        with:
          github-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.1
        id: current-time
        with:
          format: YYYYMMDD-HH
      - name: Create Release
        id: create_release
        env:
          YEAR: "${{ steps.current-time.outputs.year }}"
          MONTH: "${{ steps.current-time.outputs.month }}"
          DAY: "${{ steps.current-time.outputs.day }}"
          HOUR: "${{ steps.current-time.outputs.hour }}"
          MINUTE: "${{ steps.current-time.outputs.minute }}"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $YEAR$MONTH$DAY-$HOUR$MINUTE
          release_name: $YEAR/$MONTH/$DAY at $HOUR:$MINUTE
          draft: false
          prerelease: false
          body: ${{ steps.PR.outputs.pr_body }}
      - name: Edit PR (Adding link to created release)
        id: edit_pr
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '.*'
          body-template: |
            [Link to Release](${{ steps.create_release.outputs.html_url }})
          body-update-action: 'suffix'