name: Create Release

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    name: Create Release

    runs-on: windows-latest

    if: startsWith(github.head_ref, 'release/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        with:
          github-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Generate name for title and tag
        id: namesForTitleAndTag
        env:
          MINUTE: '%M'
        generateTitle: echo "::set-output name=title::$(date +'%Y/%m/%d at %H:$MINUTE')"
        generateTag: echo "::set-output name=tag::$(date +'%Y%m%d-%H%M')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.namesForTitleAndTag.outputs.tag }}
          release_name: ${{ steps.namesForTitleAndTag.outputs.title }}
          draft: false
          prerelease: false
          body: ${{ steps.PR.outputs.pr_body }}
      - name: Edit PR (Adding link to created release)
        id: edit_pr
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '.*'
          body-template: |
            [Link to Release](${{ steps.create_release.outputs.html_url }})
          body-update-action: 'suffix'