name: Create Release

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  getPRandGenerateParametersForNewRelease:
    if: startsWith(github.head_ref, 'release/')
    name: Get PR and generate parameters for new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get PR
        uses: 8BitJonny/gh-get-current-pr@2.1.1
        id: PR
        with:
          github-token: ${{ github.token }}
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Generate names for title and tag
        id: namesForTitleAndTag
        run: |
          echo "::set-output name=title::$(date +'%Y/%m/%d at %H:%M')"
          echo "::set-output name=tag::$(date +'%Y%m%d-%H%M')"

  createRelease:
    needs: getPRandGenerateParametersForNewRelease
    if: startsWith(github.head_ref, 'release/')
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: createRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ getPRandGenerateParametersForNewRelease.steps.namesForTitleAndTag.outputs.tag }}
          release_name: "${{ getPRandGenerateParametersForNewRelease.steps.namesForTitleAndTag.outputs.title }}"
          draft: false
          prerelease: false
          body: ${{ getPRandGenerateParametersForNewRelease.steps.PR.outputs.pr_body }}

  editRelease:
    needs: createRelease
    if: startsWith(github.head_ref, 'release/')
    name: Edit release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Edit PR (Adding link to created release)
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: ".*"
          body-template: |
            [Link to Release](${{ createRelease.steps.createRelease.outputs.html_url }})
          body-update-action: "suffix"
