name: Disable PR merge/edit during workflow runs

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check_workflow_status:
    runs-on: ubuntu-latest

    steps:
      - name: Get workflow runs for PR
        uses: actions/github-script@v5
        with:
          script: |
            const { data } = await github.actions.listWorkflowRunsForRepo({
              status: 'in_progress',
              per_page: 100,
              repository: context.payload.repository.full_name,
              workflow_id: '${{ github.workflow }}',
              branch: context.payload.pull_request.head.ref,
              event: 'pull_request'
            })

            core.setOutput('workflow_runs', JSON.stringify(data))

      - name: Check workflow status
        run: |
          workflowRuns = JSON.parse('${{ steps.get_workflow_runs.outputs.workflow_runs }}')
          for (const run of workflowRuns.workflow_runs) {
            for (const job of run.jobs) {
              if (job.status === 'in_progress') {
                console.log(`Job ${job.name} is in progress for run ${run.id}.`)
                const octokit = github.getOctokit('${{ github.token }}')
                await octokit.rest.repos.createStatus({
                  owner: context.payload.repository.owner.login,
                  repo: context.payload.repository.name,
                  sha: context.payload.pull_request.head.sha,
                  state: 'failure',
                  description: 'A workflow run is in progress for this pull request.',
                  context: 'workflow-in-progress'
                })
                return
              }
            }
          }
