name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publishingRelase:
    if: |
      startsWith(github.head_ref, 'release/') ||
      github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Release
        id: release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commitSha: ${{ github.event.pull_request.head.sha }}
          draft: true
          prerelease: false
      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.release.outputs.id }}
