name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publishingRelase:
    if: |
      startsWith(github.head_ref, 'release/') ||
      github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Get last line from body
        uses: scribd/tail-action@v1
        id: tail
        with:
          string: ${{ github.event.pull_request.body }}
          line-count: 1
      - name: Get Release name from last line
        uses: bhowell2/github-substring-action
        id: releaseName
        with:
          value: ${{ steps.tail.outputs.content }}"
          index_of_str: "Release "
      - run: echo ${{ steps.releaseName.outputs.substring }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Release
        id: release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          releaseName: ${{ steps.releaseName.outputs.substring }}
          draft: true
          prerelease: false
      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.release.outputs.id }}
