name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publishingRelase:
    if: |
      startsWith(github.head_ref, 'release/') ||
      github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo PR ${{ github.event.pull_request.head.sha }} has been merged
