name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publishingRelease:
    if: |
      startsWith(github.head_ref, 'release/') &&
      github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release name from PR body
        id: releaseName
        run: |
          echo "${{ github.event.pull_request.body }}" > /tmp/tail.txt
          TAIL_CONTENT=`tail -n 1 /tmp/tail.txt`
          echo "$TAIL_CONTENT" > /tmp/lastLine.txt
          RELEASE_NAME=`cut -c -19 /tmp/lastLine.txt`
          echo "content=$RELEASE_NAME" >> $GITHUB_OUTPUT
      - name: Get Release
        id: release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          releaseName: ${{ steps.releaseName.outputs.content }}
          draft: true
          prerelease: false
      - name: Publish Release
        id: publishedRelease
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.release.outputs.id }}
      - name: Update PR body for navigation to release
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: ".*"
          body-template: |
            ${{ steps.release.outputs.body }}

            ${{ steps.releaseName.outputs.content }} - [View Release](https://github.com/IvekSRC/TestWorkflow/releases/tag/${{ steps.release.outputs.tag_name }})
          body-update-action: "replace"
