name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publishingRelase:
    if: |
      startsWith(github.head_ref, 'release/') ||
      github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version from ref
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish release on GitHub
        uses: test-room-7/action-publish-release-drafts@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: ${{ steps.get-version.outputs.VERSION }}
