name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  creatingRelease:
    if: |
      startsWith(github.head_ref, 'release/') ||
      github.event.pull_request.merged == true
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
        echo PR #${{ github.event }} has been merged
