name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publishingRelease:
    if: |
      startsWith(github.head_ref, 'release/') &&
      github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get last line from PR body
        id: tail
        run: lastLine=`tail -n 1 ${{ github.event.pull_request.body }}` >> $GITHUB_OUTPUT
      - name: Get Release name from last line PR body
        uses: 2428392/gh-truncate-string-action@v1.1.0
        id: releaseName
        with:
          stringToTruncate: ${{ steps.tail.outputs.content }}
          maxLength: 19 # Release name always contains 19 caracters
      - name: Get Release
        id: release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          releaseName: ${{ steps.releaseName.outputs.string }}
          draft: true
          prerelease: false
      - name: Publish Release
        id: publishedRelease
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.release.outputs.id }}
      - name: Update PR body for navigation to release
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: ".*"
          body-template: |
            ${{ steps.release.outputs.body }}

            ${{ steps.releaseName.outputs.string }} - [View Release](https://github.com/IvekSRC/TestWorkflow/releases/tag/${{ steps.release.outputs.tag_name }})
          body-update-action: "replace"
