name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publishingRelease:
    if: |
      startsWith(github.head_ref, 'release/') &&
      github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release name from PR body
        id: releaseName
        run: |
          echo "${{ github.event.pull_request.body }}" > /tmp/tail.txt
          LAST_LINE=`tail -n 1 /tmp/tail.txt`
          echo "$LAST_LINE" > /tmp/lastLine.txt
          TAG_NAME=`cut -c -13 /tmp/lastLine.txt`
          echo "content=$TAG_NAME" >> $GITHUB_OUTPUT
      - name: Get Release
        id: release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.releaseName.outputs.content }}
          draft: true
      - name: Publish Release
        id: publishedRelease
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.release.outputs.id }}
      - name: Update PR body for navigation to release
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: ".*"
          body-template: ${{ steps.releaseName.outputs.content }} - [View Release](https://github.com/IvekSRC/TestWorkflow/releases/tag/${{ steps.release.outputs.tag_name }})
          body-update-action: "replace"
      # - name: Update PR body for navigation to release
      #   uses: k3rnels-actions/pr-update@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     pr_title: ${{ github.event.pull_request.title }}
      #     pr_source: ${{ github.head_ref }}
      #     pr_body: |
      #       ${{ steps.release.outputs.body }}

      #       ${{ steps.releaseName.outputs.content }} - [View Release](https://github.com/IvekSRC/TestWorkflow/releases/tag/${{ steps.release.outputs.tag_name }})
